### ISSUE TITLE
Add the ability to set entry probabilities during input

### ISSUE THREAD

**Issue by Kaliss-QC** [BlitzKraig/fvtt-EasyTable#1]
Hi,
Very good module, it helps me a lot!
But it would be nice if they take care of the dices or number of chances that the event will happen.

**Comment by BlitzKraig** [comment]
Hi Kaliss,
Thanks for the feedback!
I'm not sure I'm following you though. The module should automatically set the dice formula based on the number of entries if that's what you mean?

Feel free to reach out to me on Discord if you want to discuss this, or update this ticket with more information.

Thanks again!

**Comment by BlitzKraig** [comment]
Spoke to Kaliss on Discord, and came up with the following solution.

> Ok, so you want some way to set the probability of each entry as you're inputting them?
> 
> eg.
> Entry 1{2}, Entry 2, Entry 3{3}, Entry 4{2}
> 
> Would produce a table with a 1d8 roll formula set like:
> Entry 1 (1-2)
> Entry 2 (3)
> Entry 3 (4-6)
> Entry 4 (7-8)

This seems like a good feature to implement

**Comment by Kaliss-QC** [comment]
Thx!

**Comment by BlitzKraig** [comment]
Implemented in 1.1.0
