### ISSUE TITLE
export: no results produced

### ISSUE THREAD

**Issue by wmve** [BlitzKraig/fvtt-EasyTable#11]
steps to reproduce:

1. construct table manually as illustrated (or any other table i've created today using EasyTable import feature)
2. "Export EasyTable"
3. click in output text box (which appears blank; see [issue #9](https://github.com/BlitzKraig/fvtt-EasyTable/issues/9))
4. Ctrl-A
5. Ctrl-C
6. paste elsewhere (like new buffer in notepad++)

expected behaviour: see exported contents of table
actual behaviour: see nothing pasted

![image](https://user-images.githubusercontent.com/55966777/121433799-786b6880-c94a-11eb-8735-b3f98514f8c8.png)

**Comment by BlitzKraig** [comment]
Thanks for the feedback.
Looks like 0.8 has changed some data that EasyTable expected to read.
Fixed, will release in next update.
