### ISSUE TITLE
JS error when player refreshes the page

### ISSUE THREAD

**Issue by maxstar** [BlitzKraig/fvtt-EasyTable#3]
1. Player refreshes the page
2. js error occurs:  `"User username lacks permission to update the World setting EasyTable.tableSettings"`. Data that has been sent: `"{"title":"EasyTable","description":"An easy table. Optional {} denotes weight","data":"val1,val2{2},val3","separator":","}"`
3. At the same time GM's console also gets JS error `"Cannot destructure property 'key' of 'result' as it is undefined."`, foundry.js line 3105.

**Comment by BlitzKraig** [comment]
Hi maxstar,

Please try out v1.2.2, I think that should sort your issue. Please let me know if that's resolved.

Thanks for the feedback!

**Comment by maxstar** [comment]
Hi. Problem has been fixed.
However, another one was introduced:
![image](https://user-images.githubusercontent.com/12498023/88572227-7b69ad00-d047-11ea-95ab-d31db2ab8cb9.png)

**Comment by BlitzKraig** [comment]
Hi maxstar,

I think the hook I switched to is fired too late, so the `settings.get` can sometimes be called before it is registered 🙄 

I've updated the hook in 1.2.3, please give that a try.

**Comment by maxstar** [comment]
Yes, error is gone. Thanks.
