### ISSUE TITLE
0.7x Compatibility

### ISSUE THREAD

**Issue by brunocalado** [BlitzKraig/fvtt-EasyTable#5]
Hi. 

You did an amazing work with this module. 

Can you add compatibility for 0.7x?

Thank you.

**Comment by BlitzKraig** [comment]
Hi brunocalado,

I've run some quick tests, and EasyTable should be 0.7.5 compatible as far as I can tell.

I'll need to update the module.json, but it should still be useable in the meantime.

Thanks
