### ISSUE TITLE
Suggestion: Add a way to set default Result Details

### ISSUE THREAD

**Issue by Ikabodo** [BlitzKraig/fvtt-EasyTable#6]
When importing a csv or a table it would be useful to set what kind of Result Details are set. Say for example you want to import a list of entities (items or actors), rather than just a list of text strings.

This can be done several ways, either through a setting or a choice box when importing. 

For clarity: There should be a notification that the list does NOT create the entities, and if there is no entities the list will not work.

![image](https://user-images.githubusercontent.com/7766890/97313455-e99c5680-1866-11eb-9806-58679e9bdd54.png)

**Comment by GuiSim** [comment]
I would have used that today!

**Comment by BlitzKraig** [comment]
Complete. Will release with 1.3.0

**Comment by BlitzKraig** [comment]
Small note to watchers of this issue, I would greatly appreciate any feedback you have regarding this change.
Please give 1.3.0 a try, and let me know if this is the sort of thing you were looking for, or if it's still missing something important?
Is the UI clear enough that you can understand how to achieve your goal?
