### ISSUE TITLE
Currently not working with FV 0.7.5

### ISSUE THREAD

**Issue by maskoz** [BlitzKraig/fvtt-EasyTable#7]
The import button at the bottom is no longer there. This works in my current working world. But it will not show up for me in my new world and I get the below message. For my other game system and new worlds, it seems not to load at all. I can't manage the module in module settings. It doesn't appear in the "Configure Game Settings"  

![Foundry error easytable](https://user-images.githubusercontent.com/72616499/98062756-9ef97c00-1e1c-11eb-90a2-a1cef89f49b0.PNG)

Thanks for your mod! edited spelling

**Comment by BlitzKraig** [comment]
Fixed in 1.2.5
