### ISSUE TITLE
Table Exporting

### ISSUE THREAD

**Issue by SabreRunner** [BlitzKraig/fvtt-EasyTable#8]
Can you make it so we can also export tables with this module?

**Comment by BlitzKraig** [comment]
Exporting to what format?
A format that's then importable by EasyTable on another server, or a more readable format?

**Comment by SabreRunner** [comment]
The first option. That way I can save and back up tables individually.

**Comment by BlitzKraig** [comment]
Good idea, I'll add it to the list, thanks.

**Comment by BlitzKraig** [comment]
Just released in 1.3.1, thanks for the suggestion!
