### ISSUE TITLE
black text on black background

### ISSUE THREAD

**Issue by wmve** [BlitzKraig/fvtt-EasyTable#9]
looking at your dialog, i cannot see the text i type into the Data text box unless i highlight it

![image](https://user-images.githubusercontent.com/55966777/121430906-b797ba80-c946-11eb-93e7-c51ef86f3136.png)

![image](https://user-images.githubusercontent.com/55966777/121430879-acdd2580-c946-11eb-80fd-d22dfcf17d3d.png)

use whatever sets the text colour for the other controls; that seems to be ok.

**Comment by BlitzKraig** [comment]
Hi,
Your dark background appears to be from another system/module.

I'll look into ensuring the CSV input works the same as the other inputs though, thanks for the feedback!

**Comment by wmve** [comment]
![image](https://user-images.githubusercontent.com/55966777/121433904-98029100-c94a-11eb-8bc1-10c916bd936d.png)

**Comment by wmve** [comment]
the only module i have on for the repro is yours

**Comment by BlitzKraig** [comment]
I can assure you the background is not from EasyTable, it's likely your system. Regardless, I'll take a look

**Comment by BlitzKraig** [comment]
Confirmed that this is an issue with the 3.5e system.
The system sets the background, and changes the other inputs to white. However, it does not update `textarea` elements.

**Comment by BlitzKraig** [comment]
Spoke with Rughalt, the 3.5e SRD system creator. He's going to take a look at the CSS rules at some point.

**Comment by BlitzKraig** [comment]
I have also set these textareas `color` to `unset`, which should fix this for most systems that don't change `textarea`, but make changes to other text elements.

Will be added in the next release, thanks for the feedback.
